# Generated by Django 5.2 on 2025-04-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id_autor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('nacionalidad', models.CharField(max_length=50)),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('genero', models.CharField(max_length=50)),
                ('fecha_publicacion', models.DateField()),
                ('isbn', models.CharField(max_length=20)),
                ('num_pag', models.IntegerField()),
                ('editorial', models.CharField(max_length=100)),
                ('id_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogo.autor')),
            ],
        ),
    ]
